# Project identification
sonar.projectKey=project-aws-098
sonar.projectName=project-aws-098
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Language (auto detect usually, but optional)
# sonar.language=py

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files
sonar.exclusions=**/*.log,**/*.md,**/node_modules/**,**/venv/**,**/__pycache__/**,**/.git/**

# Test files (if any)
sonar.tests=tests

# Coverage report (optional)
# Python:
sonar.python.coverage.reportPaths=coverage.xml

# NodeJS:
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Ignore binaries
sonar.coverage.exclusions=**/*.json,**/*.yml,**/*.yaml

# Quality Gate wait (optional)
sonar.qualitygate.wait=true
